apiVersion: v1
kind: Secret
metadata:
  name: {{ template "clag.fullname" . }}-ssl
  annotations:
{{ toYaml .Values.secrets.annotations | indent 4 }}
  labels:
    app: {{ template "clag.name" . }}
    chart: {{ template "clag.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{ (.Files.Glob "certificates/*").AsSecrets | indent 2 }}

