---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "clag.fullname" . }}-runtimeconfig
  annotations:
{{ toYaml .Values.runtimeConfigmap.annotations | indent 4 }}
  labels:
    app: {{ template "clag.name" . }}
    chart: {{ template "clag.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  runtime{{ .Values.configFileName }}.yaml: |- 
    # do not remove this line: it is needed to skip possibly added UTF8 BOM.
{{ toYaml .Values.runtimeConfig | indent 4 }}
