apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "nqas.fullname" . }}
  labels:
    app: {{ template "nqas.name" . }}
    chart: {{ template "nqas.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations: 
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
{{- if .Values.ingress.tls}}
  tls:
{{ toYaml .Values.ingress.tls | indent 2 }}
{{- end}}
  rules:
  - http:
      paths:
{{- if .Values.ingress.path}}
      - path: {{ .Values.ingress.path }}
{{- else}}
      - path: /{{ .Release.Name }}
{{- end}}
        backend:
          serviceName: {{ template "nqas.fullname" . }}
{{- if eq .Values.https.enable true}}
          servicePort: nqas-svc-https
{{- else}}
          servicePort: nqas-svc-http
{{- end}}
{{- if .Values.ingress.host}}
    host: {{ .Values.ingress.host }}
{{- end}}
