---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "nqas.fullname" . }}
  labels:
    app: {{ template "nqas.name" . }}
    chart: {{ template "nqas.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    service: {{ template "nqas.fullname" . }}
{{- if .Values.image.tag }}
    image: {{ .Values.image.tag }}
{{- end }}    
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
spec:
  ports:
{{- if eq .Values.http.enable true}}
  - name: nqas-svc-http
    port: {{ .Values.service.httpPort }}
    protocol: TCP
    targetPort: nqas-http
{{- end}}
{{- if eq .Values.https.enable true}}
  - name: nqas-svc-https
    port: {{ .Values.service.httpsPort }}
    protocol: TCP
    targetPort: nqas-https
{{- end}}
  selector:
    app: {{ template "nqas.name" . }}
    release: {{ .Release.Name }}
  sessionAffinity: None
  type: {{ .Values.service.type }}
