{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "krypton-router.fullname" . }}-hpa
  annotations:
{{ toYaml .Values.autoscaling.annotations | indent 4 }}
  labels:
    app: {{ template "krypton-router.name" . }}
    chart: {{ template "krypton-router.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "krypton-router.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ tpl .Values.autoscaling.maxReplicas . }}
  metrics:
{{- with .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ . }}
{{- end }}
#{{- with .Values.autoscaling.targetMemoryUtilizationPercentage }}
#    - type: Resource
#      resource:
#        name: memory
#        target:
#          type: Utilization
#          averageUtilization: {{ . }}
#{{- end }}
{{- end }}