{{- if eq .Values.networkPolicy.enabled true}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "krypton-router.fullname" . }}-netpol
  annotations:
{{ toYaml .Values.networkPolicy.annotations | indent 4 }}
  labels:
    app: {{ template "krypton-router.name" . }}
    chart: {{ template "krypton-router.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "krypton-router.name" . }}
      release: {{ .Release.Name }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ template "krypton-router.name" . }}
    ports:
     - port: {{ .Values.config.redisClient.port }}
       protocol: TCP     
{{- if eq .Values.networkPolicy.monitoring.prometheus.enabled true}}
  - from:
    - namespaceSelector:
        matchLabels:
{{ toYaml .Values.networkPolicy.monitoring.prometheus.namespaceSelector.matchLabels | indent 10 }}
      podSelector:
        matchLabels:
{{ toYaml .Values.networkPolicy.monitoring.prometheus.podSelector.matchLabels | indent 10 }}
{{- end }}
{{- if eq .Values.networkPolicy.krypton.enabled true}}
  - from:
    - namespaceSelector:
        matchLabels:
{{ toYaml .Values.networkPolicy.krypton.namespaceSelector.matchLabels | indent 10 }}
      podSelector:    
        matchLabels:       
{{ toYaml .Values.networkPolicy.krypton.podSelector.matchLabels | indent 10 }}
{{- end }}
{{- if eq .Values.networkPolicy.ambassador.enabled true}}
  - from:
    - namespaceSelector:
        matchLabels:
{{ toYaml .Values.networkPolicy.ambassador.namespaceSelector.matchLabels | indent 10 }}
      podSelector:    
        matchLabels:       
{{ toYaml .Values.networkPolicy.ambassador.podSelector.matchLabels | indent 10 }}
{{- end }}
{{- if eq .Values.networkPolicy.client.enabled true}}
  - from:
    - namespaceSelector:
        matchLabels:
{{ toYaml .Values.networkPolicy.client.namespaceSelector.matchLabels | indent 10 }}
      podSelector:    
        matchLabels:       
{{ toYaml .Values.networkPolicy.client.podSelector.matchLabels | indent 10 }}
{{- end }}
  egress: 
  - ports:
    - port: 443
      protocol: TCP  
  - to:
    - podSelector:
        matchLabels:
          app: {{ template "krypton-router.name" . }}
    ports:
     - port: {{ .Values.config.redisClient.port }}
       protocol: TCP
{{- if eq .Values.networkPolicy.redis.enabledovernamespace true}}
  - to:
    - namespaceSelector:
        matchLabels:
{{ toYaml .Values.networkPolicy.redis.namespaceSelector.matchLabels | indent 10 }}
      podSelector:
        matchLabels:
{{ toYaml .Values.networkPolicy.redis.podSelector.matchLabels | indent 10 }}
{{- end }}         
{{- if eq .Values.networkPolicy.redis.enabledoveripport true}}
  - to:
    - ipBlock:
        cidr: {{ .Values.networkPolicy.redis.ipValue }}
    ports:
    - protocol: TCP
      port: {{ .Values.networkPolicy.redis.portValue }}
{{- end }}  
{{- if eq .Values.networkPolicy.redis.enabledoverport true}}
  - to:
    ports:
    - protocol: TCP
      port: {{ .Values.networkPolicy.redis.portValue }}
{{- end }}   
{{- if eq .Values.networkPolicy.monitoring.pushgateway.enabled true}}
  - to:
    - namespaceSelector:
        matchLabels:
{{ toYaml .Values.networkPolicy.monitoring.pushgateway.namespaceSelector.matchLabels | indent 10 }}
      podSelector:
        matchLabels:
{{ toYaml .Values.networkPolicy.monitoring.pushgateway.podSelector.matchLabels | indent 10 }}
{{- end }}
{{- if eq .Values.networkPolicy.monitoring.jaeger.enabled true}}
  - to:
    - namespaceSelector:
        matchLabels:
{{ toYaml .Values.networkPolicy.monitoring.jaeger.namespaceSelector.matchLabels | indent 10 }}
      podSelector:
        matchLabels:
{{ toYaml .Values.networkPolicy.monitoring.jaeger.podSelector.matchLabels | indent 10 }}
{{- end }}
{{- if eq .Values.networkPolicy.krypton.enabled true}}
  - to:
    - namespaceSelector:
        matchLabels:
{{ toYaml .Values.networkPolicy.krypton.namespaceSelector.matchLabels | indent 10 }}
      podSelector:    
        matchLabels:       
{{ toYaml .Values.networkPolicy.krypton.podSelector.matchLabels | indent 10 }}
{{- end }}
{{- if eq .Values.networkPolicy.ccss.enabled true}}
  - to:
    - namespaceSelector:
{{ toYaml .Values.networkPolicy.ccss.namespaceSelector | indent 8 }}
      podSelector:    
{{ toYaml .Values.networkPolicy.ccss.podSelector | indent 8 }}
{{- end }}
{{- end }}