{{- if eq .Values.prometheusOperator.enable true}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "krypton-router.fullname" . }}
  namespace: {{ .Values.prometheusOperator.namespace }}
  labels:
{{ toYaml .Values.prometheusOperator.serviceMonitor.labels | indent 4 }}
    app: {{ template "krypton-router.name" . }}
    chart: {{ template "krypton-router.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "krypton-router.name" . }}
      release: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  endpoints:
  - port: metrics-port
{{ toYaml .Values.prometheusOperator.serviceMonitor.config | indent 4 }}
{{- end}}
