{{- if and (eq .Values.commons.enabled true) (eq .Values.commons.networkPolicy.defaultPolicies true) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "commons-global.fullname" . }}-default-allow-core-dns-netpol-netpol
  annotations:
{{ toYaml .Values.commons.networkPolicy.annotations | indent 4 }}    
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    namespace.crt.nuance.com/owner: infra-addons-manager
    pool: {{ template "commons-global.name" . }}-netpol
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
    to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/cluster-service: "true"
      podSelector:
        matchLabels:
          k8s-app: kube-dns
{{- end}}