{{- if eq .Values.haproxyIngress.enabled true}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "commons-global.fullname" . }}
  labels:
{{ toYaml .Values.haproxyIngress.prometheusOperator.prometheusRulesLabels | indent 4 }}
    app: {{ template "commons-global.name" . }}
    chart: {{ template "commons-global.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: kubernetes.io/tls
data:
{{ (.Files.Glob "certificates/*").AsSecrets | indent 2 }}
{{- end}}