{{- if eq .Values.haproxyIngress.enabled true}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "commons-global.fullname" . }}-haproxy-alerts
  labels:
    alerts: haproxy
    app: {{ template "commons-global.name" . }}-haproxy-alerts
    chart: {{ template "commons-global.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  haproxy.rules.yaml: |-
    groups:
    - name: ./haproxy-alerting.rules
      rules:
      - alert: haproxy-invalid_requests_default_backend-{{ .Release.Name }}
        expr: sum by (service) (increase(haproxy_backend_http_responses_total{backend="httpback-default-backend",code="4xx",service="{{ template "commons-global.fullname" . }}-exporter"}[{{ .Values.haproxyIngress.alertConfigurations.invalidRequestsDefaultBackend.timeRange }}]))  > {{ .Values.haproxyIngress.alertConfigurations.invalidRequestsDefaultBackend.countThreshold }}
        for: 10s
        labels:
          severity: minor
        annotations:
          summary: Invalid URL request received by Haproxy ingress. Request should not get routed to default backend of haproxy. This means clients are using incorrect URL.
{{- end}}