{{- if eq .Values.minio.enabled true}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "minio.fullname" . }}-tls
  labels:
    app: {{ template "minio.name" . }}-tls
    chart: {{ template "minio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: kubernetes.io/tls
data:
{{ (.Files.Glob "minio-certificates/*").AsSecrets | indent 2 }}
{{- end}}
