{{- if and (eq .Values.networkPolicy.enabled true) (eq .Values.haproxyGrpc.enable true) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "krypton.fullname" . }}-haproxy-grpc-netpol
  annotations:
{{ toYaml .Values.networkPolicies.annotations | indent 4 }}
  labels:
    app: {{ template "krypton.name" . }}-haproxy-grpc-netpol
    chart: {{ template "krypton.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    service: {{ template "krypton.fullname" . }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "krypton.name" . }}-haproxy-grpc
      release: {{ .Release.Name }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
{{- if eq .Values.networkPolicy.monitoring.prometheus.enabled true}}
  - from:
    - namespaceSelector:
{{ toYaml .Values.networkPolicy.monitoring.prometheus.namespaceSelector | indent 8 }}
      podSelector:
{{ toYaml .Values.networkPolicy.monitoring.prometheus.podSelector | indent 8 }}
{{- end }}
{{- if eq .Values.networkPolicy.ambassador.enabled true}}
  - from:
    - namespaceSelector:
{{ toYaml .Values.networkPolicy.ambassador.namespaceSelector | indent 8 }}
      podSelector:
{{ toYaml .Values.networkPolicy.ambassador.podSelector | indent 8 }}
{{- end }}
  egress: 
  - to:
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53  
  - to:
    - podSelector:
        matchLabels:
          app: {{ template "krypton.name" . }}
          release: {{ .Release.Name }}          
{{- if eq .Values.networkPolicy.monitoring.pushgateway.enabled true}}
  - to:
    - namespaceSelector:
{{ toYaml .Values.networkPolicy.monitoring.pushgateway.namespaceSelector | indent 8 }}
      podSelector:
{{ toYaml .Values.networkPolicy.monitoring.pushgateway.podSelector | indent 8 }}
{{- end }}
{{- if eq .Values.networkPolicy.monitoring.jaeger.enabled true}}
  - to:
    - namespaceSelector:
{{ toYaml .Values.networkPolicy.monitoring.jaeger.namespaceSelector | indent 8 }}
      podSelector:
{{ toYaml .Values.networkPolicy.monitoring.jaeger.podSelector | indent 8 }}
{{- end }}
{{- end }}