{{- if eq .Values.networkPolicy.enabled true}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "krypton.fullname" . }}-netpol
  annotations:
{{ toYaml .Values.networkPolicies.annotations | indent 4 }}
  labels:
    app: {{ template "krypton.name" . }}
    chart: {{ template "krypton.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "krypton.name" . }}
      release: {{ .Release.Name }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
{{- if eq .Values.networkPolicy.monitoring.prometheus.enabled true}}
  - from:
    - namespaceSelector:
{{ toYaml .Values.networkPolicy.monitoring.prometheus.namespaceSelector | indent 8 }}
      podSelector:
{{ toYaml .Values.networkPolicy.monitoring.prometheus.podSelector | indent 8 }}
{{- end }}
{{- if eq .Values.networkPolicy.rmRegistration.enabled true}}
  - from:
    - namespaceSelector:
{{ toYaml .Values.networkPolicy.rmRegistration.namespaceSelector | indent 8 }}
      podSelector:    
{{ toYaml .Values.networkPolicy.rmRegistration.podSelector | indent 10 }}
{{- end }}
{{- if eq .Values.networkPolicy.router.enabled true}}
  - from:
    - namespaceSelector:
{{ toYaml .Values.networkPolicy.router.namespaceSelector | indent 8 }}
      podSelector:
{{ toYaml .Values.networkPolicy.router.podSelector | indent 8 }}
{{- end }}
{{- if eq .Values.networkPolicy.ambassador.enabled true}}
  - from:
    - namespaceSelector:
{{ toYaml .Values.networkPolicy.ambassador.namespaceSelector | indent 8 }}
      podSelector:
{{ toYaml .Values.networkPolicy.ambassador.podSelector | indent 8 }}
{{- end }}
  egress: 
{{- if eq .Values.networkPolicy.monitoring.pushgateway.enabled true}}
  - to:
    - namespaceSelector:
{{ toYaml .Values.networkPolicy.monitoring.pushgateway.namespaceSelector | indent 8 }}
      podSelector:
{{ toYaml .Values.networkPolicy.monitoring.pushgateway.podSelector | indent 8 }}
{{- end }}
{{- if eq .Values.networkPolicy.monitoring.jaeger.enabled true}}
  - to:
    - namespaceSelector:
{{ toYaml .Values.networkPolicy.monitoring.jaeger.namespaceSelector | indent 8 }}
      podSelector:
{{ toYaml .Values.networkPolicy.monitoring.jaeger.podSelector | indent 8 }}
{{- end }}  
{{- if eq .Values.networkPolicy.rmRegistration.enabled true}}
  - to:
    - namespaceSelector:
{{ toYaml .Values.networkPolicy.rmRegistration.namespaceSelector | indent 8 }}
      podSelector:    
{{ toYaml .Values.networkPolicy.rmRegistration.podSelector | indent 10 }}
{{- end }}
{{- if eq .Values.networkPolicy.router.enabled true}}
  - to:
    - namespaceSelector:
{{ toYaml .Values.networkPolicy.router.namespaceSelector | indent 8 }}
      podSelector:
{{ toYaml .Values.networkPolicy.router.podSelector | indent 8 }}
{{- end }}
{{- if eq .Values.networkPolicy.redis.enabledovernamespace true}}
  - to:
    - namespaceSelector:
{{ toYaml .Values.networkPolicy.redis.namespaceSelector | indent 8 }}
      podSelector:
{{ toYaml .Values.networkPolicy.redis.podSelector | indent 8 }}
{{- end }}         
{{- if eq .Values.networkPolicy.redis.enabledoveripport true}}
  - to:
    - ipBlock:
        cidr: {{ .Values.networkPolicy.redis.ipValue }}
    ports:
    - protocol: TCP
      port: {{ .Values.networkPolicy.redis.portValue }}
{{- end }}
{{- if eq .Values.networkPolicy.redis.enabledoverport true}}
  - to:
    ports:
    - protocol: TCP
      port: {{ .Values.networkPolicy.redis.portValue }}
{{- end }}
{{- if eq .Values.networkPolicy.ccss.enabled true}}
  - to:
    - namespaceSelector:
{{ toYaml .Values.networkPolicy.ccss.namespaceSelector | indent 8 }}
      podSelector:    
{{ toYaml .Values.networkPolicy.ccss.podSelector | indent 8 }}
{{- end }}
{{- if eq .Values.networkPolicy.artifactory.enabledovernamespace true}}
  - to:
    - namespaceSelector:
{{ toYaml .Values.networkPolicy.artifactory.namespaceSelector | indent 8 }}
      podSelector:
{{ toYaml .Values.networkPolicy.artifactory.podSelector | indent 8 }}
{{- end }}
{{- if eq .Values.networkPolicy.artifactory.enabledoverip true}}
  - to:
    - ipBlock:
        cidr: {{ .Values.networkPolicy.artifactory.ipValue }}
{{- end }}
{{- if eq .Values.networkPolicy.minio.enabled true}}
  - to:
    - namespaceSelector:
{{ toYaml .Values.networkPolicy.minio.namespaceSelector | indent 8 }}
      podSelector:    
{{ toYaml .Values.networkPolicy.minio.podSelector | indent 8 }}
{{- end }}
{{- if eq .Values.networkPolicy.clag.enabled true}}
  - to:
    - namespaceSelector:
{{ toYaml .Values.networkPolicy.clag.namespaceSelector | indent 8 }}
      podSelector:    
{{ toYaml .Values.networkPolicy.clag.podSelector | indent 8 }}
{{- end }}
{{- if and (eq .Values.networkPolicy.genericPorts.enabled true) (or (.Values.networkPolicy.genericPorts.tcpPortValues) (.Values.networkPolicy.genericPorts.udpPortValues)) }}
  - to:
    ports:
    {{- range  .Values.networkPolicy.genericPorts.tcpPortValues  }}
    - protocol: TCP
      port: {{ . }}        
    {{- end }}    
    {{- range  .Values.networkPolicy.genericPorts.udpPortValues  }}
    - protocol: UDP
      port: {{ . }}        
    {{- end }}    
{{- end }}
{{- end }}