apiVersion: v1
kind: Secret
metadata:
  name: {{ template "krypton.fullname" . }}-ssl
  annotations:
{{ toYaml .Values.secrets.annotations | indent 4 }}   
  labels:
    app: {{ template "krypton.name" . }}-ssl
    chart: {{ template "krypton.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{ (.Files.Glob "SSLCertificates/*").AsSecrets | indent 2 }}
