{{- if (.Values.config.callRecording) and (.Values.config.callRecording.PCIKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "krypton.fullname" . }}
  annotations:
{{ toYaml .Values.secrets.annotations | indent 4 }}   
  labels:
    app: {{ template "krypton.name" . }}
    chart: {{ template "krypton.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{ (.Files.Glob "PCIKeys/*").AsSecrets | indent 2 }}
{{- end }}